version: '3.8'
services:
  app:
    build: .
    container_name: voice-campaign-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/voice_campaign
      - SPRING_DATASOURCE_USERNAME=nurix
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: voice-campaign-postgres
    environment:
      POSTGRES_DB: voice_campaign
      POSTGRES_USER: nurix
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
